---
linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - goconst
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert

run:
  skip-dirs:
    - build
    - benchmarks
issues:
  exclude-rules:
    - linters:
        - goconst
      # Ignore GOOS warnings.
      text: "string `windows`"
    - path: _test\.go
      linters:
        - gocognit
        - goconst
